apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-users
spec:
  selector:
    matchLabels:
      app: mysql-users
      name: mysql-users
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-users
        name: mysql-users
    spec:
      containers:
      - image: mamarino/mysql-users:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
