ignore_smells:
  multiple_container:
  - name: catalogue
    containers:
    - dynatrace
  noapigateway: 
  - name: catalogue
    containers:
    - search-engine
  endpoint_based_interaction:
  - frontend
  - shipping
  wobbly:
  - frontend 
invoked_services:
- categories
- mongodb
- mysql
- cart
- rabbitmq
- shipping
- catalogue
- user-manager
ignored_manifests:
- test.yaml
