apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cart
spec:
  host: cart
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 7
      interval: 5m
      baseEjectionTime: 15m
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: products
spec:
  host: products
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 10m
      baseEjectionTime: 28m
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: user-manager
spec:
  host: user-manager
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 2m
      baseEjectionTime: 10m
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: catalogue
spec:
  host: catalogue
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 2m
      baseEjectionTime: 10m