apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-prods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-prods
  template:
    metadata:
      labels:
        app: mongo-prods
    spec:
      containers:
        - name: mamarino/mongo-prods
          image: mongo
